language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build master
    script: "./gradlew spotlessCheck check jacocoTestReport"
    if: branch = master OR type = pull_request
  - stage: release github
    if: branch =~ /release/
    script: "./gradlew check distZip distTar shadowDistTar shadowDistZip -Pversion=${TRAVIS_BRANCH#'release/'}
      && ./scripts/github-release.sh"
env:
  global:
  - secure: rqvhN6SYK1AwYvBcPVwPwzbducKayQYmq18/RXb1Oioyk9+cXiq8lkSvEbq10o1eZjHaCELqqkDxByvxZJqYbctTO8xngpt9fi7h7p1+KxRGRU6mintlsjbPF/5rHKNQC5BuLM/3cCywHGyNRiN7tKvU1/fyTl6miJCeZuW0yCPAPhr1HrYcH2ZKQqUoi/m6SqBXGRczf+cn8/tMCgTp/XDvNEmzbsPvF2u7vc1ncbmyigoCrqYmkAoYDvsfa/VXlhx6uvLk3/U3EQVgN9iYbidEnyZhEoNXaSB09yf14ulOCLC56fm7pk4R3MF6XH4lz9YT7iBJqhNxgLC1vjAHYY7YvlGL++tvR1rwuGXSOWfhoXY8zFk57HsVwuZiXs2Ooa90oiOntitWn+tGzpr6pZ0zfm4CoUnLD9BcNiXw5teEdbFto/laSsAIVWFD9FJWc+2cMH90TWGh02niRy9EnFA7MkDLiNF3Wr9dfH8BDH+R8slDLOM+w5Rnt/ymrTzMJjAbvQlayWx8XkJhn4+AKHeNbO265VabmANGL0mW+Qk7MHD1gL7PUYGuuM2XfIuB3GE/Bix1EbPmdtSclTScPtWS2S/d9polUSMfBTfvgUucPe5mWb/h6WaWEQohQRKIUsc3+RRrrffZifd8fwsUms+gtpQnhzZKTAwibE5u1no=
