language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build master
    script: "./gradlew spotlessCheck check jacocoTestReport"
    if: branch = master OR type = pull_request
  - stage: release github
    if: branch =~ /release/
    script: "./gradlew check distZip distTar shadowDistTar shadowDistZip -Pversion=${TRAVIS_BRANCH#'release/'}
      && ./scripts/github-release.sh"
env:
  global:
    secure: jTRS7UUYunF3Ixt6EQQ6DNx38rpVJFyI4tCdzkAiK5g0m1QFf9iXmwpXGN0Q0C8mkXhqza6xRdMqQ2zxUHt9+o7oIQ1/F91OEwobf2ChP8MHro7Rcs0RKgyprXHwvP1kapBfmJBVgu4zPQfiKGomVbJpkMEdmavFzYNOSrpfLr18TANMSmXwu5eGpZeZyUjczsh5On/Fup894F3N2PwTwJSsTxJ5+JI7aFMd50eHh6Nwbx1M4YSvUSKUVZULSbN88iQDSo1XSkxLff/M0ehY7jxr5Zg5rTdpbXkVU7InXBekRjAjCorJu6BVJAr3m1fuzbE+iOCDckeiQXlGcc7+/f/LOLSmVJIQmO+NgBcJSmRKsqAQoveX6PH5xiLi4yL2PYaaD59qaaxi7yJgpb6hOdPVZUdHlwjtJ69colCbnfynEKHPmn1ydqJkRzW3uV5Imafd09rFBvgwPq469jK26fQ9BBBVt47RM1iGtQwHb9CxzmT3y6Zrvr2GFWWqyBKg+g7RY7MsXJ8Jl4Ef/yHYLyEYXkfqunlcXX3bXGq+35LFaGQI6iCTm5ArBsuWgQXH7SyB9G3Obdz7xQFT90REDDPDjM186pPrze+9vOasrWKfg7hktHfrrpiqg6B1qkab16OSMZl9qMZYT7GxbSQz/ykL5KT0ooc3mP4KdGK6J9M=
