language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build master
    script: "./gradlew spotlessCheck check jacocoTestReport"
    if: branch = master OR type = pull_request
  - stage: release github
    if: branch =~ /release/
    script: "./gradlew check distZip distTar shadowDistTar shadowDistZip -Pversion=${TRAVIS_BRANCH#'release/'}
      && ./scripts/github-release.sh"
env:
  global:
    secure: lzGsEReYRMEwziiQZarwhKFD+gLjC/MmTj1Q3NgbafChdYqOVHSfBvXIP9j77RmQF/NLAk9KcNqcWaaImll1CVGMuKYja5/OK92iC2NQ/3SNrJzjuZi2RrV48Yg0LtEuPpw3LMOYHYEXy3bE36VnlBuD4b5frQt6S8W9hGKcj07vaIyb4c8iJe9b9Y2RLP5C0xMuBqCfbvM7oJ6JL5uZ/eNn1uch/c38TiTUCZ0mBoM2z/+nXI4uSvKZEE/KmJE+ExIWLGjx/+Q6OxEyh9EM/TJaQbicToRux+uaPsG+ZpZSSEi7P2LRn6iIPJukMg201F3KfWmffZEAMmrx4V5r079MGCoO1/pHaOPfZ7eP84iIb6RheJe9iGN5jAhs1tzk0qStKdtLNN3cr2IdUWAFfDVn06vKCNIIo1pW86TFVXnHCf5G6QGc1a8bqx9uUQxu9uIt2j1uYVySCYcg/+aEym0PjoQs3XnBmG3/NxKUnByeFD3L75mzGVL5vu47jCQ7XKZsrImSlOPCGtheJpGBXXW8d51ydmSgcxYJ+TpL0BpNFBgaTUAJ5TW8AJ5qmctPqmZNcP8TxMlVifpcrgbspUeYsOO6GMqRG4pziOVX6+NahDmIZpqoGNoXzHU1nWxg3Grcbd3vO6WkSy+QPcNr10gbE+jNbPXuSwMUB7rA2bM=
